CustomerRegistration/Controllers/AddressController.cs
using CustomerRegistration.Models;
using CustomerRegistration.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CustomerRegistration.Controllers
{
    public class AddressController : Controller
    {
        private readonly IAddressRepository _addressRepository;

        public AddressController(IAddressRepository addressRepository)
        {
            _addressRepository = addressRepository;
        }
        public IActionResult List()
        {
            var addresses = _addressRepository.GetAll();
            return View(addresses);
        }
        public IActionResult Details(int id)
        {
            var address = _addressRepository.GetById(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }
        public IActionResult Create()
        {
            return View();
        }

        // POST: Address/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Address address)
        {
            if (ModelState.IsValid)
            {
                _addressRepository.Add(address);
                return RedirectToAction(nameof(List));
            }
            return View(address);
        }

        public IActionResult Edit(int id)
        {
            var address = _addressRepository.GetById(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Address address)
        {
            if (ModelState.IsValid)
            {
                _addressRepository.Update(address);
                return RedirectToAction(nameof(List));
            }
            return View(address);
        }

        public IActionResult Delete(int id)
        {
            var address = _addressRepository.GetById(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var address = _addressRepository.GetById(id);
            if (address != null)
            {
                _addressRepository.Delete(id);
            }
            return RedirectToAction(nameof(List));
        }
    }
}

CustomerRegistration/Controllers/CustomerController.cs
using CustomerRegistration.Models;
using CustomerRegistration.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CustomerRegistration.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;

        public CustomerController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
        }

        public IActionResult List()
        {
            var customers = _customerRepository.GetAll();
            return View(customers);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var customer = _customerRepository.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpPost]
        public IActionResult Create(Customer customer, IFormFile logoFile)
        {
            if (ModelState.IsValid)
            {
                if (logoFile != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        logoFile.CopyTo(memoryStream);
                        customer.Logo = memoryStream.ToArray();
                    }
                }

                _customerRepository.Add(customer);
                return RedirectToAction(nameof(List));
            }
            return View(customer);
        }

        public IActionResult Edit(int id)
        {
            var customer = _customerRepository.GetById(id);
            if (customer == null) return NotFound();
            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerRepository.Update(customer);
                return RedirectToAction(nameof(List));
            }
            return View(customer);
        }

        public IActionResult Delete(int id)
        {
            var customer = _customerRepository.GetById(id);
            if (customer == null) return NotFound();
            return View(customer);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _customerRepository.Delete(id);
            return RedirectToAction(nameof(List));
        }
    }
}

CustomerRegistration/Views/Shared/_Layout.cshtml
@{
    var isAuthenticated = User.Identity.IsAuthenticated;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] CustomerRegistration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomerRegistration.styles.css" asp-append-version="true" />
</head>
<body>
    @if (isAuthenticated)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="List">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Address" asp-action="List">Endereços</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>